### ISSUE TITLE
在2004设置默认地区不能保存

### ISSUE THREAD

**Issue by moshengrenzenme** [UbuntuKylin/indicator-china-weather#1]
在2004设置默认地区不能保存，重启之后会恢复到默认沧州

**Comment by eightplus** [comment]
设计如此，重启后会自动定位当前城市。

**Comment by moshengrenzenme** [comment]
> 设计如此，重启后会自动定位当前城市。

这个设计前提是定位的准确率极高才行吧，如果设置默认的话，代表定位错误了，可是现在的话误差有点大了，目前这个定位的误差可能是省级，能不能想办法把精度提高到市级

**Comment by chenlelin** [comment]
无法收藏的原因是添加收藏城市或移除已有的收藏城市后未更新配置文件 ~/.config/kylin-weather/kylin-weather.ini

**Comment by Liang-zy** [comment]
The 20200508 version passed the test
