### ISSUE TITLE
The weather page is wrong

### ISSUE THREAD

**Issue by liumin0322** [UbuntuKylin/indicator-china-weather#3]
北京晴天，大图标显示晴天，但是下方今天显示为小雨。 
更换为长沙，两处显示也不相同。上访显示阴，下方今天显示中雨。

**Comment by eightplus** [comment]
目前正在改写新版本。

**Comment by chenlelin** [comment]
经过对比从和风天气获取的数据，UI界面显示的天气是正确的。上方大图标显示的是实时天气，下方小图标显示的是当天预报天气，存在不一样的情况。

**Comment by Liang-zy** [comment]
The 20200508 version passed the test
